name: googlesearch
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.0.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  lottie: ^3.1.3
  url_launcher: ^6.3.1
  animated_text_kit: ^4.2.3
  http: ^1.2.0
  path_provider: ^2.1.2
  record: ^5.0.4  # For recording audio

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true  # ✅ Ensures Material Icons work

  assets:
    - assets/images/mic-icon.svg
    - assets/images/more-apps.svg
    - assets/images/search-icon.svg
    - assets/images/google-logo.png
    - assets/animation.json
    - assets/harmful_words.json

  













